version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../src:/app/src
      - ../config:/app/config
      - ../requirements.txt:/app/requirements.txt
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - IN_DOCKER=true
      - WINDOWS_HOST_IP=192.168.2.25
    extra_hosts:
      - "host.docker.internal:192.168.2.25"